"""Initial migration.

Revision ID: 188a029f75d9
Revises: c1eaf12d7bb2
Create Date: 2023-02-26 18:44:34.296622

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '188a029f75d9'
down_revision = 'c1eaf12d7bb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('choose_shoes',
    sa.Column('names_id', sa.Integer(), nullable=True),
    sa.Column('sizes_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['names_id'], ['names.id'], ),
    sa.ForeignKeyConstraint(['sizes_id'], ['sizes.id'], )
    )
    with op.batch_alter_table('colours', schema=None) as batch_op:
        batch_op.drop_constraint('colours_ibfk_1', type_='foreignkey')
        batch_op.drop_column('nam_id')

    with op.batch_alter_table('sizes', schema=None) as batch_op:
        batch_op.drop_constraint('sizes_ibfk_1', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sizes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('sizes_ibfk_1', 'names', ['user_id'], ['id'])

    with op.batch_alter_table('colours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nam_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('colours_ibfk_1', 'names', ['nam_id'], ['id'])

    op.drop_table('choose_shoes')
    # ### end Alembic commands ###
