"""Initial migration.

Revision ID: 2ab26d9cadc9
Revises: 5142073c1083
Create Date: 2023-02-28 16:26:38.497752

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ab26d9cadc9'
down_revision = '5142073c1083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('choose_shoes_2')
    with op.batch_alter_table('sizes', schema=None) as batch_op:
        batch_op.drop_constraint('sizes_ibfk_1', type_='foreignkey')
        batch_op.drop_column('sizes_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sizes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sizes_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('sizes_ibfk_1', 'names', ['sizes_id'], ['id'])

    op.create_table('choose_shoes_2',
    sa.Column('names_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('colours_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['colours_id'], ['colours.id'], name='choose_shoes_2_ibfk_1'),
    sa.ForeignKeyConstraint(['names_id'], ['names.id'], name='choose_shoes_2_ibfk_2'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
