"""Initial migration.

Revision ID: 5142073c1083
Revises: 2c58a6c989c5
Create Date: 2023-02-28 15:51:28.387114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5142073c1083'
down_revision = '2c58a6c989c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('choose_shoes_2',
    sa.Column('names_id', sa.Integer(), nullable=True),
    sa.Column('colours_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['colours_id'], ['colours.id'], ),
    sa.ForeignKeyConstraint(['names_id'], ['names.id'], )
    )
    with op.batch_alter_table('choose_shoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('names_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('choose_shoes_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'names', ['names_id'], ['id'])
        batch_op.drop_column('colours_id')

    with op.batch_alter_table('colours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colours_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'names', ['colours_id'], ['id'])

    with op.batch_alter_table('sizes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sizes_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('sizes_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'names', ['sizes_id'], ['id'])
        batch_op.drop_column('names_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sizes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('names_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('sizes_ibfk_1', 'names', ['names_id'], ['id'])
        batch_op.drop_column('sizes_id')

    with op.batch_alter_table('colours', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('colours_id')

    with op.batch_alter_table('choose_shoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colours_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('choose_shoes_ibfk_3', 'colours', ['colours_id'], ['id'])
        batch_op.drop_column('names_id')

    op.drop_table('choose_shoes_2')
    # ### end Alembic commands ###
