"""Initial migration.

Revision ID: c7582bf66600
Revises: d8be18f87772
Create Date: 2023-03-11 18:18:05.230716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7582bf66600'
down_revision = 'd8be18f87772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_record', sa.Integer(), nullable=False),
    sa.Column('id_good', sa.Integer(), nullable=False),
    sa.Column('id_colour_shoes', sa.Integer(), nullable=False),
    sa.Column('id_size_shoes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('all_summ', sa.Integer(), nullable=False),
    sa.Column('id_customer', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('basket')
    # ### end Alembic commands ###
