"""Initial migration.

Revision ID: ca69105e7e36
Revises: 2ab26d9cadc9
Create Date: 2023-02-28 16:52:34.586080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca69105e7e36'
down_revision = '2ab26d9cadc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('choose_shoes_2',
    sa.Column('names_id', sa.Integer(), nullable=True),
    sa.Column('colours_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['colours_id'], ['colours.id'], ),
    sa.ForeignKeyConstraint(['names_id'], ['names.id'], )
    )
    with op.batch_alter_table('colours', schema=None) as batch_op:
        batch_op.drop_constraint('colours_ibfk_1', type_='foreignkey')
        batch_op.drop_column('colours_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colours_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('colours_ibfk_1', 'names', ['colours_id'], ['id'])

    op.drop_table('choose_shoes_2')
    # ### end Alembic commands ###
